# OpenRogue Makefile
# (C) 2026 OpenRogue Project
# SPDX-License-Identifier: zlib

# -----------------------------------------------------------------------------
# Flags
# -----------------------------------------------------------------------------

BUILD		?= debug	# Debug     | Release
PEDANTIC 	?= 0		# 0 = Off   | 1 = On
SANITIZE	?= 0		# 0 = Off   | 1 = On
V			?= 0		# 0 = Quiet | 1 = Verbose

BUILD		:= $(strip $(BUILD))
PEDANTIC	:= $(strip $(PEDANTIC))
SANITIZE	:= $(strip $(SANITIZE))
V			:= $(strip $(V))

# -----------------------------------------------------------------------------
# C / CXX standards - keep these intentionally low since again, broad compat
# -----------------------------------------------------------------------------

CXX_STANDARD 	?= -std=c++11
C_STANDARD		?= -std=c11

# -----------------------------------------------------------------------------
# Misc constants generated at config time, DO NOT EDIT.
# -----------------------------------------------------------------------------

UNAME_S 	:= $(shell uname -s)
UNAME_M 	:= $(shell uname -m)
UNAME_R 	:= $(shell uname -r)

# -----------------------------------------------------------------------------
# Toolchain stuff - generated by your compilers
# -----------------------------------------------------------------------------

ifeq ($(origin CC),default)
	CC 		:= $(firstword $(shell command -v clang gcc cc 2>/dev/null))
endif
ifeq ($(origin CXX),default)
	CXX 	:= $(firstword $(shell command -v clang++ g++ c++ 2>/dev/null))
endif

CC_VERSION	:= $(shell $(CC) --version 2>/dev/null | head -n1)
CC_TARGET	:= $(shell $(CC) -dumpmachine)

ifneq (,$(findstring clang,$(CC_VERSION)))
	CC_FAMILY := clang
else ifneq (,$(findstring gcc,$(CC_VERSION)))
	CC_FAMILY := gcc
else
	CC_FAMILY := unknown
endif

# -----------------------------------------------------------------------------
# Host + Git info
# -----------------------------------------------------------------------------

HOST_OS   		:= $(shell uname -s)
HOST_ARCH 		:= $(shell uname -m)
BUILD_DATE     	:= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LAST_COMMIT    	:= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
CURRENT_BRANCH 	:= $(shell git branch --show-current 2>/dev/null || echo unknown)

# Adding all our results to the shared flags
BUILDINFO_DEFS := \
	'-DBUILD_COMPILER="$(CC_FAMILY)"'         \
	'-DBUILD_COMPILER_VER="$(CC_VERSION)"'    \
	'-DBUILD_TARGET="$(CC_TARGET)"'           \
	'-DHOST_ARCH="$(HOST_ARCH)"'              \
	'-DHOST_OS="$(HOST_OS)"'                  \
	'-DGIT_COMMIT="$(LAST_COMMIT)"'           \
	'-DGIT_BRANCH="$(CURRENT_BRANCH)"'        \
	'-DBUILD_DATE="$(BUILD_DATE)"'

# -----------------------------------------------------------------------------
# Specialized warning flags, because cool and helpful
# -----------------------------------------------------------------------------

WARN_COMMON := \
	-Wall -Wextra -Wshadow -Wconversion -Wpointer-arith -Wunused-variable	   \
	-Wcast-qual -Wcast-align -Wformat=2 -Wundef -Wwrite-strings -Wfatal-errors \
	-Wimplicit-fallthrough -Wmissing-braces 

WARN_C 		:= \
	-Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition

WARN_CXX 	:= \
	-Wold-style-cast -Woverloaded-virtual -Wnon-virtual-dtor

WERRORS		:= \
	-Werror=return-type -Werror=null-dereference

# -----------------------------------------------------------------------------
# Source collection
# -----------------------------------------------------------------------------

SOURCE_DIR		:= $(shell pwd)/source
INCLUDE_DIR		:= $(shell pwd)/include
OUTPUT_DIR		:= $(shell pwd)/bin
EXTERNAL_DIR	:= $(shell pwd)/external
OBJECT_DIR		:= $(OUTPUT_DIR)/obj

# Usage: $(call rwildcard,<dir>,<pattern>)
rwildcard = $(foreach d,$(wildcard $(1:=/*)),$(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))

SRC_C	:= $(call rwildcard,$(SOURCE_DIR),*.c)
SRC_CXX	:= $(call rwildcard,$(SOURCE_DIR),*.cpp)

OBJ_C		:= $(patsubst $(SOURCE_DIR)/%,$(OBJECT_DIR)/%.o,$(SRC_C))
OBJ_CXX		:= $(patsubst $(SOURCE_DIR)/%,$(OBJECT_DIR)/%.o,$(SRC_CXX))
OBJECTS		:= $(OBJ_C) $(OBJ_CXX)

DEPS		:= $(OBJECTS:.o=.d)

ifneq (,$(filter MINGW% MSYS% CYGWIN%,$(UNAME_S)))
	EXE := .exe
endif
TARGET	:= $(OUTPUT_DIR)/openrogue$(EXE)

LINKER	:= $(if $(SRC_CXX),$(CXX),$(CC))

# -----------------------------------------------------------------------------
# Final assembly of flags
# -----------------------------------------------------------------------------
 
ifeq ($(BUILD),release)
	OPT_FLAGS := -O2 -DNDEBUG
else ifeq ($(BUILD),debug)
	OPT_FLAGS := -O0 -g3 -DDEBUG
else
	$(error BUILD must be 'debug' or 'release', got '$(BUILD)')
endif
 
ifeq ($(PEDANTIC),1)
	PEDANTIC_FLAGS := -pedantic
endif
 
ifeq ($(SANITIZE),1)
	SAN_FLAGS := -fsanitize=address,undefined -fno-omit-frame-pointer
endif
 
DEP_FLAGS	:= -MMD -MP
 
CPPFLAGS	:= -I$(INCLUDE_DIR) $(BUILDINFO_DEFS) $(DEP_FLAGS) $(EXTRA_CPPFLAGS)
 
CFLAGS		:= $(C_STANDARD) $(OPT_FLAGS) $(SAN_FLAGS) $(PEDANTIC_FLAGS) \
				$(WARN_COMMON) $(WARN_C) $(WERRORS) $(EXTRA_CFLAGS)
 
CXXFLAGS	:= $(CXX_STANDARD) $(OPT_FLAGS) $(SAN_FLAGS) $(PEDANTIC_FLAGS) \
				$(WARN_COMMON) $(WARN_CXX) $(WERRORS) $(EXTRA_CXXFLAGS)
 
LDFLAGS		:= $(SAN_FLAGS) $(EXTRA_LDFLAGS)
 
ifeq ($(V),1)
  Q :=
else
  Q := @
endif
LOG = $(if $(Q),@printf '  %-5s %s\n' $(1) $(2))

# -----------------------------------------------------------------------------
# Build + link rules, plus other utility functions
# -----------------------------------------------------------------------------

.DEFAULT_GOAL := all
.PHONY: all clean run info
 
all: $(TARGET)

$(TARGET): $(OBJECTS)
	@mkdir -p $(@D)
	$(call LOG,LD,$@)
	$(Q)$(LINKER) $^ -o $@ $(LDFLAGS) $(LDLIBS)
 
$(OBJECT_DIR)/%.c.o: $(SOURCE_DIR)/%.c
	@mkdir -p $(@D)
	$(call LOG,CC,$<)
	$(Q)$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@
 
$(OBJECT_DIR)/%.cpp.o: $(SOURCE_DIR)/%.cpp
	@mkdir -p $(@D)
	$(call LOG,CXX,$<)
	$(Q)$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@
 
run: $(TARGET)
	$(TARGET)
 
clean:
	rm -rf $(OBJECT_DIR) $(TARGET)

info:
	@echo "OpenRogue Information (produced by Make)"
	@echo
	@echo "[Compiler Info]"
	@echo "Found compilers: \"$(CC)\" && \"$(CXX)\""
	@echo "Compiler family:  $(CC_FAMILY)"
	@echo "Compiler version: $(CC_VERSION)"
	@echo "Compiler target:  $(CC_TARGET)"
	@echo
	@echo "[System Info]"
	@echo "System name:      $(UNAME_S)"
	@echo "System arch:      $(UNAME_M)"
	@echo "System version:   $(UNAME_R)"

-include $(DEPS)